Updated Cargo.toml dependencies, made two changes related to update o…
aya-rs/book pull request #118
Opened 2023-06-19 17:51 UTC by TawfiqAbubaker

Necessary changes to make the XDP example from the book work.
###  Changing `:ipv4` to `:i `
Because of the following aya-log change : https://github.com/aya-rs/aya/pull/599

### Adding `.unwrap()`
The type returned from .map_mut() was changed from _Result_ to _Option_

### Updating Cargo.toml
Api changes were made so the Cargo.toml had to be updated

2023-06-19 19:17 UTC, vadorovsky commented
@TawfiqAbubaker thanks for working on this! 🙏 

There are more examples which need updating, please look at the build error https://github.com/aya-rs/book/actions/runs/5314814694/jobs/9622564529?pr=118

2023-06-19 19:18 UTC, vadorovsky requested changes
@TawfiqAbubaker Thanks for working on this! 🙏 

There are more examples which need this update, please take a look at the CI error https://github.com/aya-rs/book/actions/runs/5314814694/jobs/9622564529?pr=118

2023-06-19 22:07 UTC, TawfiqAbubaker commented
> @TawfiqAbubaker Thanks for working on this! 🙏
> 
> There are more examples which need this update, please take a look at the CI error https://github.com/aya-rs/book/actions/runs/5314814694/jobs/9622564529?pr=118

I just added another commit, I think it needs you to run the build to see if it's working? I'm not familiar with the build system you have on here. Let me know if it's not working or if I need to add something else

2023-06-20 17:20 UTC, tamird commented on examples/xdp-hello/xdp-hello/Cargo.toml
> +aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = ["async_tokio"] }
I think `branch = "main"` can be removed here and everywhere; we should use whatever the default branch is (which is defined by the server).

2023-06-26 20:09 UTC, tamird commented
Looks like some instances of `:ipv6` need to be updated as well.

2023-06-27 14:20 UTC, merged