docs: add kubernetes sigs to who's using Aya
aya-rs/book pull request #141
Opened 2023-10-26 16:47 UTC by shaneutt

This patch adds Kubernetes SIGs as official users of Aya, now that https://github.com/kubernetes-sigs/blixt is an official CNCF project under Kubernetes SIG Network.

2023-10-26 16:48 UTC, shaneutt commented
/cc @astoycos @alessandrod @vadorovsky

2023-10-26 18:32 UTC, astoycos commented
Super nit can you use something like this instead 

![image](https://github.com/aya-rs/book/assets/23533892/21750ff5-e99e-4277-9427-40b02497ad80)

I think it would look better in the website rendering

2023-10-26 18:39 UTC, shaneutt commented
Sure, done.

2023-10-26 19:50 UTC, vadorovsky requested changes
I would keep the list alphabetically sorted (to avoid treating some projects or companies as "more important", even if not intended). So before Red Hat and after Exein. :)

2023-10-26 20:26 UTC, shaneutt commented
> I would keep the list alphabetically sorted (to avoid treating some projects or companies as "more important", even if not intended). So before Red Hat and after Exein. :)

Done!

2023-10-27 02:34 UTC, vadorovsky approved these changes

2023-10-27 02:35 UTC, merged