fix myapp-02 example build and run instructions
aya-rs/book pull request #21
Opened 2022-01-14 12:27 UTC by dmitris

Fixes #20.

2022-01-15 13:41 UTC, dave-tucker requested changes
Please `unwrap()` vs using `ok_or` since the only way you would get an error here is if you had made a typo in the section name

2022-01-15 13:41 UTC, dave-tucker commented on examples/myapp-02/myapp/src/main.rs
> +    let probe: &mut Xdp = bpf.program_mut("xdp").ok_or(anyhow::anyhow!("failed to load bpf program"))?.try_into()?;
```suggestion
    let probe: &mut Xdp = bpf.program_mut("xdp").unwrap().try_into()?;
```

2022-01-15 13:41 UTC, dave-tucker commented on examples/myapp-03/myapp/src/main.rs
> +    let probe: &mut Xdp = bpf.program_mut("xdp").ok_or(anyhow::anyhow!("failed to load bpf program"))?.try_into()?;
```suggestion
    let probe: &mut Xdp = bpf.program_mut("xdp").unwrap().try_into()?;
```

2022-01-16 08:23 UTC, dmitris commented on examples/myapp-03/myapp/src/main.rs
> +    let probe: &mut Xdp = bpf.program_mut("xdp").ok_or(anyhow::anyhow!("failed to load bpf program"))?.try_into()?;
changed in a18bef3

2022-01-16 08:23 UTC, dmitris commented on examples/myapp-02/myapp/src/main.rs
> +    let probe: &mut Xdp = bpf.program_mut("xdp").ok_or(anyhow::anyhow!("failed to load bpf program"))?.try_into()?;
changed to `unwrap` in a18bef3

2022-01-17 10:00 UTC, dmitris commented
> Please `unwrap()` vs using `ok_or` since the only way you would get an error here is if you had made a typo in the section name

done - changed to:
`let probe: &mut Xdp = bpf.program_mut("xdp").unwrap().try_into()?;`

2022-01-17 15:07 UTC, dave-tucker approved these changes

2022-01-17 15:07 UTC, merged